import { Component } from '@angular/core';
import {App, NavController, NavParams, Platform, ToastController} from 'ionic-angular';
import { Games } from '../../providers/providers';
import {HomePage} from "../home/home";

export interface Slide {
  grupa: 'A'
  g1_data: 'A'
  g1_czas: 'A'
  g1_A_flag: 'A'
  g1_A: 'A'
  g1_A_score: 'A'
  g1_B_score: 'A'
  g1_B: 'A'
  g1_B_flag: 'A'
  g2_data: 'A'
  g2_czas: 'A'
  g2_A_flag: 'A'
  g2_A: 'A'
  g2_A_score: 'A'
  g2_B_score: 'A'
  g2_B: 'A'
  g2_B_flag: 'A'
  g3_data: 'A'
  g3_czas: 'A'
  g3_A_flag: 'A'
  g3_A: 'A'
  g3_A_score: 'A'
  g3_B_score: 'A'
  g3_B: 'A'
  g3_B_flag: 'A'
  g4_data: 'A'
  g4_czas: 'A'
  g4_A_flag: 'A'
  g4_A: 'A'
  g4_A_score: 'A'
  g4_B_score: 'A'
  g4_B: 'A'
  g4_B_flag: 'A'
  g5_data: 'A'
  g5_czas: 'A'
  g5_A_flag: 'A'
  g5_A: 'A'
  g5_A_score: 'A'
  g5_B_score: 'A'
  g5_B: 'A'
  g5_B_flag: 'A'
  g6_data: 'A'
  g6_czas: 'A'
  g6_A_flag: 'A'
  g6_A: 'A'
  g6_A_score: 'A'
  g6_B_score: 'A'
  g6_B: 'A'
  g6_B_flag: 'A'
  g7_data: 'A'
  g7_czas: 'A'
  g7_A_flag: 'A'
  g7_A: 'A'
  g7_A_score: 'A'
  g7_B_score: 'A'
  g7_B: 'A'
  g7_B_flag: 'A'
  g8_data: 'A'
  g8_czas: 'A'
  g8_A_flag: 'A'
  g8_A: 'A'
  g8_A_score: 'A'
  g8_B_score: 'A'
  g8_B: 'A'
  g8_B_flag: 'A'
}

@Component({
  selector: 'page-list',
  templateUrl: 'list.html'
})

export class ListPage {
  slides: Slide[];
  dir: string = 'ltr';
  private gamesErrorString: string;

  constructor(public navCtrl: NavController,
              public navParams: NavParams,
              public games: Games,
              public toastCtrl: ToastController,
              private app: App,
              public platform: Platform) {
    this.dir = platform.dir();
    this.gamesErrorString = "Error while getting Games from the server!!!";

    this.getGames();
  }

  getGames() {
    // Attempt to get games through games service
    this.games.get_games().subscribe((resp) => {
      //var g1_date =

      this.slides = [
        {
          grupa: resp[0]['phase_group'],
          g1_data: resp[0]['date_time_ts'].split(" ")[0],
          g1_czas: resp[0]['date_time_ts'].split(" ")[1],
          g1_A_flag: resp[0]['flag_a'],
          g1_A: resp[0]['team_a'],
          g1_A_score: resp[0]['score_team_a_90']!=null ? resp[0]['score_team_a_90'] : "-",
          g1_B_score: resp[0]['score_team_b_90']!=null ? resp[0]['score_team_b_90'] : "-",
          g1_B: resp[0]['team_b'],
          g1_B_flag: resp[0]['flag_b'],
          g2_data: resp[1]['date_time_ts'].split(" ")[0],
          g2_czas: resp[1]['date_time_ts'].split(" ")[1],
          g2_A_flag: resp[1]['flag_a'],
          g2_A: resp[1]['team_a'],
          g2_A_score: resp[1]['score_team_a_90']!=null ? resp[1]['score_team_a_90'] : "-",
          g2_B_score: resp[1]['score_team_b_90']!=null ? resp[1]['score_team_b_90'] : "-",
          g2_B: resp[1]['team_b'],
          g2_B_flag: resp[1]['flag_b'],
          g3_data: resp[2]['date_time_ts'].split(" ")[0],
          g3_czas: resp[2]['date_time_ts'].split(" ")[1],
          g3_A_flag: resp[2]['flag_a'],
          g3_A: resp[2]['team_a'],
          g3_A_score: resp[2]['score_team_a_90']!=null ? resp[2]['score_team_a_90'] : "-",
          g3_B_score: resp[2]['score_team_b_90']!=null ? resp[2]['score_team_b_90'] : "-",
          g3_B: resp[2]['team_b'],
          g3_B_flag: resp[2]['flag_b'],
          g4_data: resp[3]['date_time_ts'].split(" ")[0],
          g4_czas: resp[3]['date_time_ts'].split(" ")[1],
          g4_A_flag: resp[3]['flag_a'],
          g4_A: resp[3]['team_a'],
          g4_A_score: resp[3]['score_team_a_90']!=null ? resp[3]['score_team_a_90'] : "-",
          g4_B_score: resp[3]['score_team_b_90']!=null ? resp[3]['score_team_b_90'] : "-",
          g4_B: resp[3]['team_b'],
          g4_B_flag: resp[3]['flag_b'],
          g5_data: resp[4]['date_time_ts'].split(" ")[0],
          g5_czas: resp[4]['date_time_ts'].split(" ")[1],
          g5_A_flag: resp[4]['flag_a'],
          g5_A: resp[4]['team_a'],
          g5_A_score: resp[4]['score_team_a_90']!=null ? resp[4]['score_team_a_90'] : "-",
          g5_B_score: resp[4]['score_team_b_90']!=null ? resp[4]['score_team_b_90'] : "-",
          g5_B: resp[4]['team_b'],
          g5_B_flag: resp[4]['flag_b'],
          g6_data: resp[5]['date_time_ts'].split(" ")[0],
          g6_czas: resp[5]['date_time_ts'].split(" ")[1],
          g6_A_flag: resp[5]['flag_a'],
          g6_A: resp[5]['team_a'],
          g6_A_score: resp[5]['score_team_a_90']!=null ? resp[5]['score_team_a_90'] : "-",
          g6_B_score: resp[5]['score_team_b_90']!=null ? resp[5]['score_team_b_90'] : "-",
          g6_B: resp[5]['team_b'],
          g6_B_flag: resp[5]['flag_b'],
          g7_data: "",
          g7_czas: "",
          g7_A_flag: "",
          g7_A: "",
          g7_A_score: "-",
          g7_B_score: "-",
          g7_B: "",
          g7_B_flag: "",
          g8_data: "",
          g8_czas: "",
          g8_A_flag: "",
          g8_A: "",
          g8_A_score: "-",
          g8_B_score: "-",
          g8_B: "",
          g8_B_flag: "",
        },
        {
          grupa: resp[6]['phase_group'],
          g1_data: resp[6]['date_time_ts'].split(" ")[0],
          g1_czas: resp[6]['date_time_ts'].split(" ")[1],
          g1_A_flag: resp[6]['flag_a'],
          g1_A: resp[6]['team_a'],
          g1_A_score: resp[6]['score_team_a_90']!=null ? resp[6]['score_team_a_90'] : "-",
          g1_B_score: resp[6]['score_team_b_90']!=null ? resp[6]['score_team_b_90'] : "-",
          g1_B: resp[6]['team_b'],
          g1_B_flag: resp[6]['flag_b'],
          g2_data: resp[7]['date_time_ts'].split(" ")[0],
          g2_czas: resp[7]['date_time_ts'].split(" ")[1],
          g2_A_flag: resp[7]['flag_a'],
          g2_A: resp[7]['team_a'],
          g2_A_score: resp[7]['score_team_a_90']!=null ? resp[7]['score_team_a_90'] : "-",
          g2_B_score: resp[7]['score_team_b_90']!=null ? resp[7]['score_team_b_90'] : "-",
          g2_B: resp[7]['team_b'],
          g2_B_flag: resp[7]['flag_b'],
          g3_data: resp[8]['date_time_ts'].split(" ")[0],
          g3_czas: resp[8]['date_time_ts'].split(" ")[1],
          g3_A_flag: resp[8]['flag_a'],
          g3_A: resp[8]['team_a'],
          g3_A_score: resp[8]['score_team_a_90']!=null ? resp[8]['score_team_a_90'] : "-",
          g3_B_score: resp[8]['score_team_b_90']!=null ? resp[8]['score_team_b_90'] : "-",
          g3_B: resp[8]['team_b'],
          g3_B_flag: resp[8]['flag_b'],
          g4_data: resp[9]['date_time_ts'].split(" ")[0],
          g4_czas: resp[9]['date_time_ts'].split(" ")[1],
          g4_A_flag: resp[9]['flag_a'],
          g4_A: resp[9]['team_a'],
          g4_A_score: resp[9]['score_team_a_90']!=null ? resp[9]['score_team_a_90'] : "-",
          g4_B_score: resp[9]['score_team_b_90']!=null ? resp[9]['score_team_b_90'] : "-",
          g4_B: resp[9]['team_b'],
          g4_B_flag: resp[9]['flag_b'],
          g5_data: resp[10]['date_time_ts'].split(" ")[0],
          g5_czas: resp[10]['date_time_ts'].split(" ")[1],
          g5_A_flag: resp[10]['flag_a'],
          g5_A: resp[10]['team_a'],
          g5_A_score: resp[10]['score_team_a_90']!=null ? resp[10]['score_team_a_90'] : "-",
          g5_B_score: resp[10]['score_team_b_90']!=null ? resp[10]['score_team_b_90'] : "-",
          g5_B: resp[10]['team_b'],
          g5_B_flag: resp[10]['flag_b'],
          g6_data: resp[11]['date_time_ts'].split(" ")[0],
          g6_czas: resp[11]['date_time_ts'].split(" ")[1],
          g6_A_flag: resp[11]['flag_a'],
          g6_A: resp[11]['team_a'],
          g6_A_score: resp[11]['score_team_a_90']!=null ? resp[11]['score_team_a_90'] : "-",
          g6_B_score: resp[11]['score_team_b_90']!=null ? resp[11]['score_team_b_90'] : "-",
          g6_B: resp[11]['team_b'],
          g6_B_flag: resp[11]['flag_b'],
          g7_data: "",
          g7_czas: "",
          g7_A_flag: "",
          g7_A: "",
          g7_A_score: "-",
          g7_B_score: "-",
          g7_B: "",
          g7_B_flag: "",
          g8_data: "",
          g8_czas: "",
          g8_A_flag: "",
          g8_A: "",
          g8_A_score: "-",
          g8_B_score: "-",
          g8_B: "",
          g8_B_flag: "",
        },
        {
          grupa: resp[12]['phase_group'],
          g1_data: resp[12]['date_time_ts'].split(" ")[0],
          g1_czas: resp[12]['date_time_ts'].split(" ")[1],
          g1_A_flag: resp[12]['flag_a'],
          g1_A: resp[12]['team_a'],
          g1_A_score: resp[12]['score_team_a_90']!=null ? resp[12]['score_team_a_90'] : "-",
          g1_B_score: resp[12]['score_team_b_90']!=null ? resp[12]['score_team_b_90'] : "-",
          g1_B: resp[12]['team_b'],
          g1_B_flag: resp[12]['flag_b'],
          g2_data: resp[13]['date_time_ts'].split(" ")[0],
          g2_czas: resp[13]['date_time_ts'].split(" ")[1],
          g2_A_flag: resp[13]['flag_a'],
          g2_A: resp[13]['team_a'],
          g2_A_score: resp[13]['score_team_a_90']!=null ? resp[13]['score_team_a_90'] : "-",
          g2_B_score: resp[13]['score_team_b_90']!=null ? resp[13]['score_team_b_90'] : "-",
          g2_B: resp[13]['team_b'],
          g2_B_flag: resp[13]['flag_b'],
          g3_data: resp[14]['date_time_ts'].split(" ")[0],
          g3_czas: resp[14]['date_time_ts'].split(" ")[1],
          g3_A_flag: resp[14]['flag_a'],
          g3_A: resp[14]['team_a'],
          g3_A_score: resp[14]['score_team_a_90']!=null ? resp[14]['score_team_a_90'] : "-",
          g3_B_score: resp[14]['score_team_b_90']!=null ? resp[14]['score_team_b_90'] : "-",
          g3_B: resp[14]['team_b'],
          g3_B_flag: resp[14]['flag_b'],
          g4_data: resp[15]['date_time_ts'].split(" ")[0],
          g4_czas: resp[15]['date_time_ts'].split(" ")[1],
          g4_A_flag: resp[15]['flag_a'],
          g4_A: resp[15]['team_a'],
          g4_A_score: resp[15]['score_team_a_90']!=null ? resp[15]['score_team_a_90'] : "-",
          g4_B_score: resp[15]['score_team_b_90']!=null ? resp[15]['score_team_b_90'] : "-",
          g4_B: resp[15]['team_b'],
          g4_B_flag: resp[15]['flag_b'],
          g5_data: resp[16]['date_time_ts'].split(" ")[0],
          g5_czas: resp[16]['date_time_ts'].split(" ")[1],
          g5_A_flag: resp[16]['flag_a'],
          g5_A: resp[16]['team_a'],
          g5_A_score: resp[16]['score_team_a_90']!=null ? resp[16]['score_team_a_90'] : "-",
          g5_B_score: resp[16]['score_team_b_90']!=null ? resp[16]['score_team_b_90'] : "-",
          g5_B: resp[16]['team_b'],
          g5_B_flag: resp[16]['flag_b'],
          g6_data: resp[17]['date_time_ts'].split(" ")[0],
          g6_czas: resp[17]['date_time_ts'].split(" ")[1],
          g6_A_flag: resp[17]['flag_a'],
          g6_A: resp[17]['team_a'],
          g6_A_score: resp[17]['score_team_a_90']!=null ? resp[17]['score_team_a_90'] : "-",
          g6_B_score: resp[17]['score_team_b_90']!=null ? resp[17]['score_team_b_90'] : "-",
          g6_B: resp[17]['team_b'],
          g6_B_flag: resp[17]['flag_b'],
          g7_data: "",
          g7_czas: "",
          g7_A_flag: "",
          g7_A: "",
          g7_A_score: "-",
          g7_B_score: "-",
          g7_B: "",
          g7_B_flag: "",
          g8_data: "",
          g8_czas: "",
          g8_A_flag: "",
          g8_A: "",
          g8_A_score: "-",
          g8_B_score: "-",
          g8_B: "",
          g8_B_flag: "",
        },
        {
          grupa: resp[18]['phase_group'],
          g1_data: resp[18]['date_time_ts'].split(" ")[0],
          g1_czas: resp[18]['date_time_ts'].split(" ")[1],
          g1_A_flag: resp[18]['flag_a'],
          g1_A: resp[18]['team_a'],
          g1_A_score: resp[18]['score_team_a_90']!=null ? resp[18]['score_team_a_90'] : "-",
          g1_B_score: resp[18]['score_team_b_90']!=null ? resp[18]['score_team_b_90'] : "-",
          g1_B: resp[18]['team_b'],
          g1_B_flag: resp[18]['flag_b'],
          g2_data: resp[19]['date_time_ts'].split(" ")[0],
          g2_czas: resp[19]['date_time_ts'].split(" ")[1],
          g2_A_flag: resp[19]['flag_a'],
          g2_A: resp[19]['team_a'],
          g2_A_score: resp[19]['score_team_a_90']!=null ? resp[19]['score_team_a_90'] : "-",
          g2_B_score: resp[19]['score_team_b_90']!=null ? resp[19]['score_team_b_90'] : "-",
          g2_B: resp[19]['team_b'],
          g2_B_flag: resp[19]['flag_b'],
          g3_data: resp[20]['date_time_ts'].split(" ")[0],
          g3_czas: resp[20]['date_time_ts'].split(" ")[1],
          g3_A_flag: resp[20]['flag_a'],
          g3_A: resp[20]['team_a'],
          g3_A_score: resp[20]['score_team_a_90']!=null ? resp[20]['score_team_a_90'] : "-",
          g3_B_score: resp[20]['score_team_b_90']!=null ? resp[20]['score_team_b_90'] : "-",
          g3_B: resp[20]['team_b'],
          g3_B_flag: resp[20]['flag_b'],
          g4_data: resp[21]['date_time_ts'].split(" ")[0],
          g4_czas: resp[21]['date_time_ts'].split(" ")[1],
          g4_A_flag: resp[21]['flag_a'],
          g4_A: resp[21]['team_a'],
          g4_A_score: resp[21]['score_team_a_90']!=null ? resp[21]['score_team_a_90'] : "-",
          g4_B_score: resp[21]['score_team_b_90']!=null ? resp[21]['score_team_b_90'] : "-",
          g4_B: resp[21]['team_b'],
          g4_B_flag: resp[21]['flag_b'],
          g5_data: resp[22]['date_time_ts'].split(" ")[0],
          g5_czas: resp[22]['date_time_ts'].split(" ")[1],
          g5_A_flag: resp[22]['flag_a'],
          g5_A: resp[22]['team_a'],
          g5_A_score: resp[22]['score_team_a_90']!=null ? resp[22]['score_team_a_90'] : "-",
          g5_B_score: resp[22]['score_team_b_90']!=null ? resp[22]['score_team_b_90'] : "-",
          g5_B: resp[22]['team_b'],
          g5_B_flag: resp[22]['flag_b'],
          g6_data: resp[23]['date_time_ts'].split(" ")[0],
          g6_czas: resp[23]['date_time_ts'].split(" ")[1],
          g6_A_flag: resp[23]['flag_a'],
          g6_A: resp[23]['team_a'],
          g6_A_score: resp[23]['score_team_a_90']!=null ? resp[23]['score_team_a_90'] : "-",
          g6_B_score: resp[23]['score_team_b_90']!=null ? resp[23]['score_team_b_90'] : "-",
          g6_B: resp[23]['team_b'],
          g6_B_flag: resp[23]['flag_b'],
          g7_data: "",
          g7_czas: "",
          g7_A_flag: "",
          g7_A: "",
          g7_A_score: "-",
          g7_B_score: "-",
          g7_B: "",
          g7_B_flag: "",
          g8_data: "",
          g8_czas: "",
          g8_A_flag: "",
          g8_A: "",
          g8_A_score: "-",
          g8_B_score: "-",
          g8_B: "",
          g8_B_flag: "",
        },
        {
          grupa: resp[24]['phase_group'],
          g1_data: resp[24]['date_time_ts'].split(" ")[0],
          g1_czas: resp[24]['date_time_ts'].split(" ")[1],
          g1_A_flag: resp[24]['flag_a'],
          g1_A: resp[24]['team_a'],
          g1_A_score: resp[24]['score_team_a_90']!=null ? resp[24]['score_team_a_90'] : "-",
          g1_B_score: resp[24]['score_team_b_90']!=null ? resp[24]['score_team_b_90'] : "-",
          g1_B: resp[24]['team_b'],
          g1_B_flag: resp[24]['flag_b'],
          g2_data: resp[25]['date_time_ts'].split(" ")[0],
          g2_czas: resp[25]['date_time_ts'].split(" ")[1],
          g2_A_flag: resp[25]['flag_a'],
          g2_A: resp[25]['team_a'],
          g2_A_score: resp[25]['score_team_a_90']!=null ? resp[25]['score_team_a_90'] : "-",
          g2_B_score: resp[25]['score_team_b_90']!=null ? resp[25]['score_team_b_90'] : "-",
          g2_B: resp[25]['team_b'],
          g2_B_flag: resp[25]['flag_b'],
          g3_data: resp[26]['date_time_ts'].split(" ")[0],
          g3_czas: resp[26]['date_time_ts'].split(" ")[1],
          g3_A_flag: resp[26]['flag_a'],
          g3_A: resp[26]['team_a'],
          g3_A_score: resp[26]['score_team_a_90']!=null ? resp[26]['score_team_a_90'] : "-",
          g3_B_score: resp[26]['score_team_b_90']!=null ? resp[26]['score_team_b_90'] : "-",
          g3_B: resp[26]['team_b'],
          g3_B_flag: resp[26]['flag_b'],
          g4_data: resp[27]['date_time_ts'].split(" ")[0],
          g4_czas: resp[27]['date_time_ts'].split(" ")[1],
          g4_A_flag: resp[27]['flag_a'],
          g4_A: resp[27]['team_a'],
          g4_A_score: resp[27]['score_team_a_90']!=null ? resp[27]['score_team_a_90'] : "-",
          g4_B_score: resp[27]['score_team_b_90']!=null ? resp[27]['score_team_b_90'] : "-",
          g4_B: resp[27]['team_b'],
          g4_B_flag: resp[27]['flag_b'],
          g5_data: resp[28]['date_time_ts'].split(" ")[0],
          g5_czas: resp[28]['date_time_ts'].split(" ")[1],
          g5_A_flag: resp[28]['flag_a'],
          g5_A: resp[28]['team_a'],
          g5_A_score: resp[28]['score_team_a_90']!=null ? resp[28]['score_team_a_90'] : "-",
          g5_B_score: resp[28]['score_team_b_90']!=null ? resp[28]['score_team_b_90'] : "-",
          g5_B: resp[28]['team_b'],
          g5_B_flag: resp[28]['flag_b'],
          g6_data: resp[29]['date_time_ts'].split(" ")[0],
          g6_czas: resp[29]['date_time_ts'].split(" ")[1],
          g6_A_flag: resp[29]['flag_a'],
          g6_A: resp[29]['team_a'],
          g6_A_score: resp[29]['score_team_a_90']!=null ? resp[29]['score_team_a_90'] : "-",
          g6_B_score: resp[29]['score_team_b_90']!=null ? resp[29]['score_team_b_90'] : "-",
          g6_B: resp[29]['team_b'],
          g6_B_flag: resp[29]['flag_b'],
          g7_data: "",
          g7_czas: "",
          g7_A_flag: "",
          g7_A: "",
          g7_A_score: "-",
          g7_B_score: "-",
          g7_B: "",
          g7_B_flag: "",
          g8_data: "",
          g8_czas: "",
          g8_A_flag: "",
          g8_A: "",
          g8_A_score: "-",
          g8_B_score: "-",
          g8_B: "",
          g8_B_flag: "",
        },
        {
          grupa: resp[30]['phase_group'],
          g1_data: resp[30]['date_time_ts'].split(" ")[0],
          g1_czas: resp[30]['date_time_ts'].split(" ")[1],
          g1_A_flag: resp[30]['flag_a'],
          g1_A: resp[30]['team_a'],
          g1_A_score: resp[30]['score_team_a_90']!=null ? resp[30]['score_team_a_90'] : "-",
          g1_B_score: resp[30]['score_team_b_90']!=null ? resp[30]['score_team_b_90'] : "-",
          g1_B: resp[30]['team_b'],
          g1_B_flag: resp[30]['flag_b'],
          g2_data: resp[31]['date_time_ts'].split(" ")[0],
          g2_czas: resp[31]['date_time_ts'].split(" ")[1],
          g2_A_flag: resp[31]['flag_a'],
          g2_A: resp[31]['team_a'],
          g2_A_score: resp[31]['score_team_a_90']!=null ? resp[31]['score_team_a_90'] : "-",
          g2_B_score: resp[31]['score_team_b_90']!=null ? resp[31]['score_team_b_90'] : "-",
          g2_B: resp[31]['team_b'],
          g2_B_flag: resp[31]['flag_b'],
          g3_data: resp[32]['date_time_ts'].split(" ")[0],
          g3_czas: resp[32]['date_time_ts'].split(" ")[1],
          g3_A_flag: resp[32]['flag_a'],
          g3_A: resp[32]['team_a'],
          g3_A_score: resp[32]['score_team_a_90']!=null ? resp[32]['score_team_a_90'] : "-",
          g3_B_score: resp[32]['score_team_b_90']!=null ? resp[32]['score_team_b_90'] : "-",
          g3_B: resp[32]['team_b'],
          g3_B_flag: resp[32]['flag_b'],
          g4_data: resp[33]['date_time_ts'].split(" ")[0],
          g4_czas: resp[33]['date_time_ts'].split(" ")[1],
          g4_A_flag: resp[33]['flag_a'],
          g4_A: resp[33]['team_a'],
          g4_A_score: resp[33]['score_team_a_90']!=null ? resp[33]['score_team_a_90'] : "-",
          g4_B_score: resp[33]['score_team_b_90']!=null ? resp[33]['score_team_b_90'] : "-",
          g4_B: resp[33]['team_b'],
          g4_B_flag: resp[33]['flag_b'],
          g5_data: resp[34]['date_time_ts'].split(" ")[0],
          g5_czas: resp[34]['date_time_ts'].split(" ")[1],
          g5_A_flag: resp[34]['flag_a'],
          g5_A: resp[34]['team_a'],
          g5_A_score: resp[34]['score_team_a_90']!=null ? resp[34]['score_team_a_90'] : "-",
          g5_B_score: resp[34]['score_team_b_90']!=null ? resp[34]['score_team_b_90'] : "-",
          g5_B: resp[34]['team_b'],
          g5_B_flag: resp[34]['flag_b'],
          g6_data: resp[35]['date_time_ts'].split(" ")[0],
          g6_czas: resp[35]['date_time_ts'].split(" ")[1],
          g6_A_flag: resp[35]['flag_a'],
          g6_A: resp[35]['team_a'],
          g6_A_score: resp[35]['score_team_a_90']!=null ? resp[35]['score_team_a_90'] : "-",
          g6_B_score: resp[35]['score_team_b_90']!=null ? resp[35]['score_team_b_90'] : "-",
          g6_B: resp[35]['team_b'],
          g6_B_flag: resp[35]['flag_b'],
          g7_data: "",
          g7_czas: "",
          g7_A_flag: "",
          g7_A: "",
          g7_A_score: "-",
          g7_B_score: "-",
          g7_B: "",
          g7_B_flag: "",
          g8_data: "",
          g8_czas: "",
          g8_A_flag: "",
          g8_A: "",
          g8_A_score: "-",
          g8_B_score: "-",
          g8_B: "",
          g8_B_flag: "",
        },
        {
          grupa: resp[36]['phase_group'],
          g1_data: resp[36]['date_time_ts'].split(" ")[0],
          g1_czas: resp[36]['date_time_ts'].split(" ")[1],
          g1_A_flag: resp[36]['flag_a'],
          g1_A: resp[36]['team_a'],
          g1_A_score: resp[36]['score_team_a_90']!=null ? resp[36]['score_team_a_90'] : "-",
          g1_B_score: resp[36]['score_team_b_90']!=null ? resp[36]['score_team_b_90'] : "-",
          g1_B: resp[36]['team_b'],
          g1_B_flag: resp[36]['flag_b'],
          g2_data: resp[37]['date_time_ts'].split(" ")[0],
          g2_czas: resp[37]['date_time_ts'].split(" ")[1],
          g2_A_flag: resp[37]['flag_a'],
          g2_A: resp[37]['team_a'],
          g2_A_score: resp[37]['score_team_a_90']!=null ? resp[37]['score_team_a_90'] : "-",
          g2_B_score: resp[37]['score_team_b_90']!=null ? resp[37]['score_team_b_90'] : "-",
          g2_B: resp[37]['team_b'],
          g2_B_flag: resp[37]['flag_b'],
          g3_data: resp[38]['date_time_ts'].split(" ")[0],
          g3_czas: resp[38]['date_time_ts'].split(" ")[1],
          g3_A_flag: resp[38]['flag_a'],
          g3_A: resp[38]['team_a'],
          g3_A_score: resp[38]['score_team_a_90']!=null ? resp[38]['score_team_a_90'] : "-",
          g3_B_score: resp[38]['score_team_b_90']!=null ? resp[38]['score_team_b_90'] : "-",
          g3_B: resp[38]['team_b'],
          g3_B_flag: resp[38]['flag_b'],
          g4_data: resp[39]['date_time_ts'].split(" ")[0],
          g4_czas: resp[39]['date_time_ts'].split(" ")[1],
          g4_A_flag: resp[39]['flag_a'],
          g4_A: resp[39]['team_a'],
          g4_A_score: resp[39]['score_team_a_90']!=null ? resp[39]['score_team_a_90'] : "-",
          g4_B_score: resp[39]['score_team_b_90']!=null ? resp[39]['score_team_b_90'] : "-",
          g4_B: resp[39]['team_b'],
          g4_B_flag: resp[39]['flag_b'],
          g5_data: resp[40]['date_time_ts'].split(" ")[0],
          g5_czas: resp[40]['date_time_ts'].split(" ")[1],
          g5_A_flag: resp[40]['flag_a'],
          g5_A: resp[40]['team_a'],
          g5_A_score: resp[40]['score_team_a_90']!=null ? resp[40]['score_team_a_90'] : "-",
          g5_B_score: resp[40]['score_team_b_90']!=null ? resp[40]['score_team_b_90'] : "-",
          g5_B: resp[40]['team_b'],
          g5_B_flag: resp[40]['flag_b'],
          g6_data: resp[41]['date_time_ts'].split(" ")[0],
          g6_czas: resp[41]['date_time_ts'].split(" ")[1],
          g6_A_flag: resp[41]['flag_a'],
          g6_A: resp[41]['team_a'],
          g6_A_score: resp[41]['score_team_a_90']!=null ? resp[41]['score_team_a_90'] : "-",
          g6_B_score: resp[41]['score_team_b_90']!=null ? resp[41]['score_team_b_90'] : "-",
          g6_B: resp[41]['team_b'],
          g6_B_flag: resp[41]['flag_b'],
          g7_data: "",
          g7_czas: "",
          g7_A_flag: "",
          g7_A: "",
          g7_A_score: "-",
          g7_B_score: "-",
          g7_B: "",
          g7_B_flag: "",
          g8_data: "",
          g8_czas: "",
          g8_A_flag: "",
          g8_A: "",
          g8_A_score: "-",
          g8_B_score: "-",
          g8_B: "",
          g8_B_flag: "",
        },
        {
          grupa: resp[42]['phase_group'],
          g1_data: resp[42]['date_time_ts'].split(" ")[0],
          g1_czas: resp[42]['date_time_ts'].split(" ")[1],
          g1_A_flag: resp[42]['flag_a'],
          g1_A: resp[42]['team_a'],
          g1_A_score: resp[42]['score_team_a_90']!=null ? resp[42]['score_team_a_90'] : "-",
          g1_B_score: resp[42]['score_team_b_90']!=null ? resp[42]['score_team_b_90'] : "-",
          g1_B: resp[42]['team_b'],
          g1_B_flag: resp[42]['flag_b'],
          g2_data: resp[43]['date_time_ts'].split(" ")[0],
          g2_czas: resp[43]['date_time_ts'].split(" ")[1],
          g2_A_flag: resp[43]['flag_a'],
          g2_A: resp[43]['team_a'],
          g2_A_score: resp[43]['score_team_a_90']!=null ? resp[43]['score_team_a_90'] : "-",
          g2_B_score: resp[43]['score_team_b_90']!=null ? resp[43]['score_team_b_90'] : "-",
          g2_B: resp[43]['team_b'],
          g2_B_flag: resp[43]['flag_b'],
          g3_data: resp[44]['date_time_ts'].split(" ")[0],
          g3_czas: resp[44]['date_time_ts'].split(" ")[1],
          g3_A_flag: resp[44]['flag_a'],
          g3_A: resp[44]['team_a'],
          g3_A_score: resp[44]['score_team_a_90']!=null ? resp[44]['score_team_a_90'] : "-",
          g3_B_score: resp[44]['score_team_b_90']!=null ? resp[44]['score_team_b_90'] : "-",
          g3_B: resp[44]['team_b'],
          g3_B_flag: resp[44]['flag_b'],
          g4_data: resp[45]['date_time_ts'].split(" ")[0],
          g4_czas: resp[45]['date_time_ts'].split(" ")[1],
          g4_A_flag: resp[45]['flag_a'],
          g4_A: resp[45]['team_a'],
          g4_A_score: resp[45]['score_team_a_90']!=null ? resp[45]['score_team_a_90'] : "-",
          g4_B_score: resp[45]['score_team_b_90']!=null ? resp[45]['score_team_b_90'] : "-",
          g4_B: resp[45]['team_b'],
          g4_B_flag: resp[45]['flag_b'],
          g5_data: resp[46]['date_time_ts'].split(" ")[0],
          g5_czas: resp[46]['date_time_ts'].split(" ")[1],
          g5_A_flag: resp[46]['flag_a'],
          g5_A: resp[46]['team_a'],
          g5_A_score: resp[46]['score_team_a_90']!=null ? resp[46]['score_team_a_90'] : "-",
          g5_B_score: resp[46]['score_team_b_90']!=null ? resp[46]['score_team_b_90'] : "-",
          g5_B: resp[46]['team_b'],
          g5_B_flag: resp[46]['flag_b'],
          g6_data: resp[47]['date_time_ts'].split(" ")[0],
          g6_czas: resp[47]['date_time_ts'].split(" ")[1],
          g6_A_flag: resp[47]['flag_a'],
          g6_A: resp[47]['team_a'],
          g6_A_score: resp[47]['score_team_a_90']!=null ? resp[47]['score_team_a_90'] : "-",
          g6_B_score: resp[47]['score_team_b_90']!=null ? resp[47]['score_team_b_90'] : "-",
          g6_B: resp[47]['team_b'],
          g6_B_flag: resp[47]['flag_b'],
          g7_data: "",
          g7_czas: "",
          g7_A_flag: "",
          g7_A: "",
          g7_A_score: "-",
          g7_B_score: "-",
          g7_B: "",
          g7_B_flag: "",
          g8_data: "",
          g8_czas: "",
          g8_A_flag: "",
          g8_A: "",
          g8_A_score: "-",
          g8_B_score: "-",
          g8_B: "",
          g8_B_flag: "",
        },
        {
          grupa: resp[48]['phase_group'],
          g1_data: resp[48]['date_time_ts'].split(" ")[0],
          g1_czas: resp[48]['date_time_ts'].split(" ")[1],
          g1_A_flag: resp[48]['flag_a'],
          g1_A: resp[48]['team_a'],
          g1_A_score: resp[48]['score_team_a_90']!=null ? resp[48]['score_team_a_90'] : "-",
          g1_B_score: resp[48]['score_team_b_90']!=null ? resp[48]['score_team_b_90'] : "-",
          g1_B: resp[48]['team_b'],
          g1_B_flag: resp[48]['flag_b'],
          g2_data: resp[49]['date_time_ts'].split(" ")[0],
          g2_czas: resp[49]['date_time_ts'].split(" ")[1],
          g2_A_flag: resp[49]['flag_a'],
          g2_A: resp[49]['team_a'],
          g2_A_score: resp[49]['score_team_a_90']!=null ? resp[49]['score_team_a_90'] : "-",
          g2_B_score: resp[49]['score_team_b_90']!=null ? resp[49]['score_team_b_90'] : "-",
          g2_B: resp[49]['team_b'],
          g2_B_flag: resp[49]['flag_b'],
          g3_data: resp[50]['date_time_ts'].split(" ")[0],
          g3_czas: resp[50]['date_time_ts'].split(" ")[1],
          g3_A_flag: resp[50]['flag_a'],
          g3_A: resp[50]['team_a'],
          g3_A_score: resp[50]['score_team_a_90']!=null ? resp[50]['score_team_a_90'] : "-",
          g3_B_score: resp[50]['score_team_b_90']!=null ? resp[50]['score_team_b_90'] : "-",
          g3_B: resp[50]['team_b'],
          g3_B_flag: resp[50]['flag_b'],
          g4_data: resp[51]['date_time_ts'].split(" ")[0],
          g4_czas: resp[51]['date_time_ts'].split(" ")[1],
          g4_A_flag: resp[51]['flag_a'],
          g4_A: resp[51]['team_a'],
          g4_A_score: resp[51]['score_team_a_90']!=null ? resp[51]['score_team_a_90'] : "-",
          g4_B_score: resp[51]['score_team_b_90']!=null ? resp[51]['score_team_b_90'] : "-",
          g4_B: resp[51]['team_b'],
          g4_B_flag: resp[51]['flag_b'],
          g5_data: resp[52]['date_time_ts'].split(" ")[0],
          g5_czas: resp[52]['date_time_ts'].split(" ")[1],
          g5_A_flag: resp[52]['flag_a'],
          g5_A: resp[52]['team_a'],
          g5_A_score: resp[52]['score_team_a_90']!=null ? resp[52]['score_team_a_90'] : "-",
          g5_B_score: resp[52]['score_team_b_90']!=null ? resp[52]['score_team_b_90'] : "-",
          g5_B: resp[52]['team_b'],
          g5_B_flag: resp[52]['flag_b'],
          g6_data: resp[53]['date_time_ts'].split(" ")[0],
          g6_czas: resp[53]['date_time_ts'].split(" ")[1],
          g6_A_flag: resp[53]['flag_a'],
          g6_A: resp[53]['team_a'],
          g6_A_score: resp[53]['score_team_a_90']!=null ? resp[53]['score_team_a_90'] : "-",
          g6_B_score: resp[53]['score_team_b_90']!=null ? resp[53]['score_team_b_90'] : "-",
          g6_B: resp[53]['team_b'],
          g6_B_flag: resp[53]['flag_b'],
          g7_data: resp[54]['date_time_ts'].split(" ")[0],
          g7_czas: resp[54]['date_time_ts'].split(" ")[1],
          g7_A_flag: resp[54]['flag_a'],
          g7_A: resp[54]['team_a'],
          g7_A_score: resp[54]['score_team_a_90']!=null ? resp[54]['score_team_a_90'] : "-",
          g7_B_score: resp[54]['score_team_b_90']!=null ? resp[54]['score_team_b_90'] : "-",
          g7_B: resp[54]['team_b'],
          g7_B_flag: resp[54]['flag_b'],
          g8_data: resp[55]['date_time_ts'].split(" ")[0],
          g8_czas: resp[55]['date_time_ts'].split(" ")[1],
          g8_A_flag: resp[55]['flag_a'],
          g8_A: resp[55]['team_a'],
          g8_A_score: resp[55]['score_team_a_90']!=null ? resp[55]['score_team_a_90'] : "-",
          g8_B_score: resp[55]['score_team_b_90']!=null ? resp[55]['score_team_b_90'] : "-",
          g8_B: resp[55]['team_b'],
          g8_B_flag: resp[55]['flag_b'],
        },
        {
          grupa: resp[56]['phase_group'],
          g1_data: resp[56]['date_time_ts'].split(" ")[0],
          g1_czas: resp[56]['date_time_ts'].split(" ")[1],
          g1_A_flag: resp[56]['flag_a'],
          g1_A: resp[56]['team_a'],
          g1_A_score: resp[56]['score_team_a_90']!=null ? resp[56]['score_team_a_90'] : "-",
          g1_B_score: resp[56]['score_team_b_90']!=null ? resp[56]['score_team_b_90'] : "-",
          g1_B: resp[56]['team_b'],
          g1_B_flag: resp[56]['flag_b'],
          g2_data: resp[57]['date_time_ts'].split(" ")[0],
          g2_czas: resp[57]['date_time_ts'].split(" ")[1],
          g2_A_flag: resp[57]['flag_a'],
          g2_A: resp[57]['team_a'],
          g2_A_score: resp[57]['score_team_a_90']!=null ? resp[57]['score_team_a_90'] : "-",
          g2_B_score: resp[57]['score_team_b_90']!=null ? resp[57]['score_team_b_90'] : "-",
          g2_B: resp[57]['team_b'],
          g2_B_flag: resp[57]['flag_b'],
          g3_data: resp[58]['date_time_ts'].split(" ")[0],
          g3_czas: resp[58]['date_time_ts'].split(" ")[1],
          g3_A_flag: resp[58]['flag_a'],
          g3_A: resp[58]['team_a'],
          g3_A_score: resp[58]['score_team_a_90']!=null ? resp[58]['score_team_a_90'] : "-",
          g3_B_score: resp[58]['score_team_b_90']!=null ? resp[58]['score_team_b_90'] : "-",
          g3_B: resp[58]['team_b'],
          g3_B_flag: resp[58]['flag_b'],
          g4_data: resp[59]['date_time_ts'].split(" ")[0],
          g4_czas: resp[59]['date_time_ts'].split(" ")[1],
          g4_A_flag: resp[59]['flag_a'],
          g4_A: resp[59]['team_a'],
          g4_A_score: resp[59]['score_team_a_90']!=null ? resp[59]['score_team_a_90'] : "-",
          g4_B_score: resp[59]['score_team_b_90']!=null ? resp[59]['score_team_b_90'] : "-",
          g4_B: resp[59]['team_b'],
          g4_B_flag: resp[59]['flag_b'],
          g5_data: "",
          g5_czas: "",
          g5_A_flag: "",
          g5_A: "",
          g5_A_score: "-",
          g5_B_score: "-",
          g5_B: "",
          g5_B_flag: "",
          g6_data: "",
          g6_czas: "",
          g6_A_flag: "",
          g6_A: "",
          g6_A_score: "-",
          g6_B_score: "-",
          g6_B: "",
          g6_B_flag: "",
          g7_data: "",
          g7_czas: "",
          g7_A_flag: "",
          g7_A: "",
          g7_A_score: "-",
          g7_B_score: "-",
          g7_B: "",
          g7_B_flag: "",
          g8_data: "",
          g8_czas: "",
          g8_A_flag: "",
          g8_A: "",
          g8_A_score: "-",
          g8_B_score: "-",
          g8_B: "",
          g8_B_flag: "",
        },
        {
          grupa: resp[60]['phase_group'],
          g1_data: resp[60]['date_time_ts'].split(" ")[0],
          g1_czas: resp[60]['date_time_ts'].split(" ")[1],
          g1_A_flag: resp[60]['flag_a'],
          g1_A: resp[60]['team_a'],
          g1_A_score: resp[60]['score_team_a_90']!=null ? resp[60]['score_team_a_90'] : "-",
          g1_B_score: resp[60]['score_team_b_90']!=null ? resp[60]['score_team_b_90'] : "-",
          g1_B: resp[60]['team_b'],
          g1_B_flag: resp[60]['flag_b'],
          g2_data: resp[61]['date_time_ts'].split(" ")[0],
          g2_czas: resp[61]['date_time_ts'].split(" ")[1],
          g2_A_flag: resp[61]['flag_a'],
          g2_A: resp[61]['team_a'],
          g2_A_score: resp[61]['score_team_a_90']!=null ? resp[61]['score_team_a_90'] : "-",
          g2_B_score: resp[61]['score_team_b_90']!=null ? resp[61]['score_team_b_90'] : "-",
          g2_B: resp[61]['team_b'],
          g2_B_flag: resp[61]['flag_b'],
          g3_data: "",
          g3_czas: "",
          g3_A_flag: "",
          g3_A: "",
          g3_A_score: "-",
          g3_B_score: "-",
          g3_B: "",
          g3_B_flag: "",
          g4_data: "",
          g4_czas: "",
          g4_A_flag: "",
          g4_A: "",
          g4_A_score: "-",
          g4_B_score: "-",
          g4_B: "",
          g4_B_flag: "",
          g5_data: "",
          g5_czas: "",
          g5_A_flag: "",
          g5_A: "",
          g5_A_score: "-",
          g5_B_score: "-",
          g5_B: "",
          g5_B_flag: "",
          g6_data: "",
          g6_czas: "",
          g6_A_flag: "",
          g6_A: "",
          g6_A_score: "-",
          g6_B_score: "-",
          g6_B: "",
          g6_B_flag: "",
          g7_data: "",
          g7_czas: "",
          g7_A_flag: "",
          g7_A: "",
          g7_A_score: "-",
          g7_B_score: "-",
          g7_B: "",
          g7_B_flag: "",
          g8_data: "",
          g8_czas: "",
          g8_A_flag: "",
          g8_A: "",
          g8_A_score: "-",
          g8_B_score: "-",
          g8_B: "",
          g8_B_flag: "",
        },
        {
          grupa: resp[62]['phase_group'],
          g1_data: resp[62]['date_time_ts'].split(" ")[0],
          g1_czas: resp[62]['date_time_ts'].split(" ")[1],
          g1_A_flag: resp[62]['flag_a'],
          g1_A: resp[62]['team_a'],
          g1_A_score: resp[62]['score_team_a_90']!=null ? resp[62]['score_team_a_90'] : "-",
          g1_B_score: resp[62]['score_team_b_90']!=null ? resp[62]['score_team_b_90'] : "-",
          g1_B: resp[62]['team_b'],
          g1_B_flag: resp[62]['flag_b'],
          g2_data: "",
          g2_czas: "",
          g2_A_flag: "",
          g2_A: "",
          g2_A_score: "-",
          g2_B_score: "-",
          g2_B: "",
          g2_B_flag: "",
          g3_data: "",
          g3_czas: "",
          g3_A_flag: "",
          g3_A: "",
          g3_A_score: "-",
          g3_B_score: "-",
          g3_B: "",
          g3_B_flag: "",
          g4_data: "",
          g4_czas: "",
          g4_A_flag: "",
          g4_A: "",
          g4_A_score: "-",
          g4_B_score: "-",
          g4_B: "",
          g4_B_flag: "",
          g5_data: "",
          g5_czas: "",
          g5_A_flag: "",
          g5_A: "",
          g5_A_score: "-",
          g5_B_score: "-",
          g5_B: "",
          g5_B_flag: "",
          g6_data: "",
          g6_czas: "",
          g6_A_flag: "",
          g6_A: "",
          g6_A_score: "-",
          g6_B_score: "-",
          g6_B: "",
          g6_B_flag: "",
          g7_data: "",
          g7_czas: "",
          g7_A_flag: "",
          g7_A: "",
          g7_A_score: "-",
          g7_B_score: "-",
          g7_B: "",
          g7_B_flag: "",
          g8_data: "",
          g8_czas: "",
          g8_A_flag: "",
          g8_A: "",
          g8_A_score: "-",
          g8_B_score: "-",
          g8_B: "",
          g8_B_flag: "",
        },
        {
          grupa: resp[63]['phase_group'],
          g1_data: resp[63]['date_time_ts'].split(" ")[0],
          g1_czas: resp[63]['date_time_ts'].split(" ")[1],
          g1_A_flag: resp[63]['flag_a'],
          g1_A: resp[63]['team_a'],
          g1_A_score: resp[63]['score_team_a_90']!=null ? resp[63]['score_team_a_90'] : "-",
          g1_B_score: resp[63]['score_team_b_90']!=null ? resp[63]['score_team_b_90'] : "-",
          g1_B: resp[63]['team_b'],
          g1_B_flag: resp[63]['flag_b'],
          g2_data: "",
          g2_czas: "",
          g2_A_flag: "",
          g2_A: "",
          g2_A_score: "-",
          g2_B_score: "-",
          g2_B: "",
          g2_B_flag: "",
          g3_data: "",
          g3_czas: "",
          g3_A_flag: "",
          g3_A: "",
          g3_A_score: "-",
          g3_B_score: "-",
          g3_B: "",
          g3_B_flag: "",
          g4_data: "",
          g4_czas: "",
          g4_A_flag: "",
          g4_A: "",
          g4_A_score: "-",
          g4_B_score: "-",
          g4_B: "",
          g4_B_flag: "",
          g5_data: "",
          g5_czas: "",
          g5_A_flag: "",
          g5_A: "",
          g5_A_score: "-",
          g5_B_score: "-",
          g5_B: "",
          g5_B_flag: "",
          g6_data: "",
          g6_czas: "",
          g6_A_flag: "",
          g6_A: "",
          g6_A_score: "-",
          g6_B_score: "-",
          g6_B: "",
          g6_B_flag: "",
          g7_data: "",
          g7_czas: "",
          g7_A_flag: "",
          g7_A: "",
          g7_A_score: "-",
          g7_B_score: "-",
          g7_B: "",
          g7_B_flag: "",
          g8_data: "",
          g8_czas: "",
          g8_A_flag: "",
          g8_A: "",
          g8_A_score: "-",
          g8_B_score: "-",
          g8_B: "",
          g8_B_flag: "",
        },
      ];
    }, (err) => {

      this.app.getRootNav().setRoot(HomePage);

      // Unable to sign up
      let toast = this.toastCtrl.create({
        message: this.gamesErrorString,
        duration: 3000,
        position: 'bottom'
      });
      toast.present();
    });
  }

  itemTapped(event, item) {
    // That's right, we're pushing to ourselves!
    this.navCtrl.push(ListPage, {
      item: item
    });
  }
}
